image: golang:1.25.8-alpine3.23

stages:
  - build
  - lint
  - test
  - docs
  - pages
  - release

.buildah:
  image: quay.io/buildah/stable
  stage: build
  variables:
    BUILDAH_ISOLATION: chroot
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    # Login to Docker Hub for per-user rate limits
    - echo "$DOCKER_PASSWORD" | buildah login --username "$DOCKER_USER" --password-stdin docker.io
  rules:
    - if: $CI_REGISTRY
    - if: $CI_REGISTRY_IMAGE
    - if: $CI_REGISTRY_USER
    - if: $CI_REGISTRY_PASSWORD
    - if: $BUILD_CONTEXT
    - if: $BUILD_DOCKERFILE
    - if: $IMAGE
    - if: $TAG
  script:
    - buildah bud --layers --cache-from $CI_REGISTRY_IMAGE/cache --cache-to $CI_REGISTRY_IMAGE/cache -f ${BUILD_DOCKERFILE} -t ${IMAGE}:${TAG} ${BUILD_CONTEXT}
    - buildah push ${IMAGE}:${TAG}

.buildah-sha:
  extends: .buildah
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      script:
        - buildah bud --layers --cache-from $CI_REGISTRY_IMAGE/cache --cache-to $CI_REGISTRY_IMAGE/cache -f ${BUILD_DOCKERFILE} -t ${IMAGE}:${CI_COMMIT_SHA} ${BUILD_CONTEXT}
        - buildah push ${IMAGE}:${CI_COMMIT_SHA}
    - when: always

build-chantico:
  extends: .buildah-sha
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        TAG: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        TAG: latest
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG: $CI_COMMIT_REF_SLUG
  variables:
    BUILD_DOCKERFILE: Dockerfile
    BUILD_CONTEXT: .
    IMAGE: "$CI_REGISTRY_IMAGE/chantico"
    TAG: latest

build-snmp-mock:
  extends: .buildah-sha
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        TAG: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        TAG: latest
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG: $CI_COMMIT_REF_SLUG
  variables:
    BUILD_DOCKERFILE: Dockerfile.snmp-mock
    BUILD_CONTEXT: .
    IMAGE: "$CI_REGISTRY_IMAGE/chantico-snmp-mock"
    TAG: latest

chantico-fmt:
  stage: lint
  needs: []
  allow_failure: true # Make it a warning instead for now.
  script:
    - |
      files=$(gofmt -l .)
      if [ -n "$files" ]; then
        echo "The following files are not formatted according to https://go.dev/blog/gofmt:"
        echo "$files"
        exit 1
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

chantico-vet:
  stage: lint
  needs: []
  allow_failure: true # Make it a warning instead for now.
  script:
    - go vet ./...
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

golangci-lint:
  stage: lint
  image: "golangci/golangci-lint:v2.11.4"
  needs: []
  allow_failure: true # Make it a warning instead for now.
  script:
    - golangci-lint run --output.code-climate.path=gl-code-quality-report.json
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  artifacts:
    when: always
    reports:
      codequality: gl-code-quality-report.json

go-test:
  stage: test
  variables:
    TESTS: ./internal/...
  before_script:
    - apk add --no-cache git
    - go install github.com/t-yuki/gocover-cobertura@latest
    - go install gotest.tools/gotestsum@latest
  script:
    - $(go env GOPATH)/bin/gotestsum --junitfile report.xml --format testname -- -v -coverprofile=coverage.out $TESTS
    - go tool cover -func coverage.out
    - $(go env GOPATH)/bin/gocover-cobertura < coverage.out > coverage.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml
  # https://docs.gitlab.com/ci/testing/code_coverage/?tab=Go#coverage-regex-patterns
  coverage: /total:\s+\(statements\)\s+\d+.\d+%/
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: $CI_COMMIT_TAG

osv-scanner:
  stage: test
  rules: 
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  
  image:
    name: ghcr.io/google/osv-scanner-action:v2.3.3
    entrypoint: [""] # Override entry point
  allow_failure: true # Make it a warning instead for now; to allow deployment/review by team.
  script: # osv-scanner recursively scans the project for dependencies
    - echo "OSV_JOB_ID=$CI_JOB_ID" >> scanner.env
    - osv-scanner --licenses="Apache-2.0,BSD-3-Clause,BSD-2-Clause,ISC,MIT" --call-analysis -r . --format json --output osv-scanner-report.json || true
    - osv-reporter --new osv-scanner-report.json --output html:osv-scanner-report.html
  artifacts:
    paths:
      - osv-scanner-report.json
      - osv-scanner-report.html
    reports:
      dotenv: scanner.env
    when: always

osv-scan-review:
  stage: test
  needs:
    - job: osv-scanner
      artifacts: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo "Publishing OSV scan artifacts"
  environment:
    name: scan/$CI_COMMIT_REF_SLUG
    url: "$ARTIFACT_URL/osv-scanner-report.html"
    on_stop: stop-scan-review
  variables:
    ARTIFACT_URL: "https://ipcei-cis-misd-sustainable-datacenters.ci.tno.nl/-/wp2/energy-domain-controller/chantico/-/jobs/$OSV_JOB_ID/artifacts"

stop-scan-review:
  stage: pages
  script:
    - echo "Stopping review app for osv-scanner"
  environment:
    name: scan/$CI_COMMIT_REF_SLUG
    action: stop
  when: manual

docs:
  stage: docs
  script:
    - go install go.abhg.dev/doc2go@v0.11.0
    - doc2go -embed -highlight classes:monokai -basename _index.html -out docs/technical/api -frontmatter docs/hugo/frontmatter.tmpl -rel-link-style $REL_LINK_STYLE -internal ./...
    - find docs/technical/api -type f -name '*.html' -print0 | xargs -0 sed -i 's/_index\.html/index.html/g'
    - 'printf -- "---\ntitle: "Changelog"\nweight: 60\nmain:\n  parent: technical\n  weight: 50\n---\n%s" "$(sed -E -e "s|\(([0-9a-f]{7,})\)|([\1](https://github.com/chantico-project/chantico/commit/\1))|" -e "s|^## ([0-9]+\.[0-9]+\.[0-9]+)|## [\1](https://github.com/chantico-project/chantico/releases/tag/v\1)|" CHANGELOG.md)" > docs/technical/changelog.md'
    - mkdir -p docs/assets/css/extended
    - doc2go -highlight monokai -highlight-print-css > docs/assets/css/extended/highlight.css
    - 'echo ":root {--main-width: 1024px}.chroma {background-color: #24273a !important}" > docs/assets/css/extended/width.css'
  artifacts:
    paths:
      - docs
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        REL_LINK_STYLE: "directory"
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
      variables:
        REL_LINK_STYLE: "index"

hugo-preview:
  image: "hugomods/hugo:exts"
  stage: pages
  artifacts:
    paths:
      - docs/hugo/public
    reports:
      dotenv: docs/hugo/preview.env
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: "$ARTIFACT_URL/index.html"
    on_stop: stop-review
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    ARTIFACT_URL: "https://ipcei-cis-misd-sustainable-datacenters.ci.tno.nl/-/wp2/energy-domain-controller/chantico/-/jobs/$CI_JOB_ID/artifacts/docs/hugo/public"
  dependencies:
    - docs
  script:
    - cd docs/hugo && hugo --baseURL="$ARTIFACT_URL/" --config "hugo.toml,hugo.preview.toml"
    - echo PREVIEW_URL="$ARTIFACT_URL/index.html" >> preview.env
    - echo "PREVIEW_JOB_ID=$CI_JOB_ID" >> preview.env
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

docs-check-links:
  stage: pages
  needs:
    - job: hugo-preview
      artifacts: true
  allow_failure: true # Make it a warning instead for now.
  variables:
    ARTIFACT_HOST: "https://ipcei-cis-misd-sustainable-datacenters.ci.tno.nl"
    ARTIFACT_PATH: "-/wp2/energy-domain-controller/chantico/-/jobs/$PREVIEW_JOB_ID/artifacts/docs/hugo/public"
  script:
    - |
      cat <<'EOF' > server.go
      package main
      import (
        "log"
        "net/http"
      )
      func main() {
        log.Println("Serving on :8000")
        log.Fatal(http.ListenAndServe(":8000", http.FileServer(http.Dir("."))))
      }
      EOF

    # mirror GitLab artifact path
    - mkdir -p -- "$(dirname -- "$ARTIFACT_PATH")"
    - mv docs/hugo/public -- "$ARTIFACT_PATH"

    # start server
    - go run server.go &
    - SERVER_PID=$!

    - go install github.com/raviqqe/muffet/v2@v2.11.2
    - muffet --verbose --include="http://localhost:8000/$ARTIFACT_PATH" "http://localhost:8000/$ARTIFACT_PATH/index.html" | sed "s|http://localhost:8000|${ARTIFACT_HOST}|g"

    # cleanup
    - kill $SERVER_PID
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

stop-review:
  stage: pages
  script:
    - echo "Stopping review app for hugo-preview"
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  when: manual

pages:
  image: "hugomods/hugo:exts"
  stage: pages
  pages:
    publish: docs/hugo/public
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  dependencies:
    - docs
  script:
    - cd docs/hugo && hugo
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

build-release-test:
  image: "goreleaser/goreleaser:v2.14.3"
  stage: release
  variables:
    GIT_DEPTH: 0
  script:
    - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release && chmod +x ./semantic-release
    - ./semantic-release --update ./config/deployment/Chart.yaml --allow-initial-development-versions --dry --no-ci || true
    - goreleaser build --config .goreleaser.gitlab.yaml --clean --skip validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        CI_COMMIT_BRANCH: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME'
  when: manual

release:
  image: "goreleaser/goreleaser:v2.14.3"
  stage: release
  allow_failure: true # semantic release exits with code 1 if there are no changes
  variables:
    GIT_DEPTH: 0
    SEMREL_OPTIONS: --allow-initial-development-versions --allow-no-changes
    GITHUB_REPOSITORY: "chantico-project/chantico"
  script:
    - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ./semantic-release && chmod +x ./semantic-release
    - git config --global user.email "semantic-release@gitlab"
    - git config --global user.name "go-semantic-release"
    - ./semantic-release --changelog CHANGELOG.md --prepend-changelog --dry -f $SEMREL_OPTIONS
    - if [ ! -f .version-unreleased ]; then exit 0; fi
    - VERSION=$(cat .version-unreleased)
    # Commit updated versions in files if changed
    - sed -E -i "s/^VERSION([ ?]*)=.*/VERSION\1= $VERSION/" Makefile
    - 'sed -i "s/^version:.*/version: $VERSION/" config/deployment/Chart.yaml'
    - 'sed -i "s/appVersion:.*/appVersion: \"v$VERSION\"/" config/deployment/Chart.yaml'
    - 'sed -i "s|org.opencontainers.image.version:.*|org.opencontainers.image.version: $VERSION|" config/deployment/Chart.yaml'
    - 'sed -Ei "s|org.opencontainers.image.description: \"(.*)--version.*\`\"|org.opencontainers.image.description: \"\1--version $VERSION\`\"|" config/deployment/Chart.yaml'
    - |
      if ! git diff --quiet; then
        git add CHANGELOG.md Makefile config/deployment/Chart.yaml
        git commit -m "bump version to v$VERSION [skip ci]"
        git push https://oauth2:${GITLAB_TOKEN}@ci.tno.nl/gitlab/${CI_PROJECT_PATH}.git HEAD:${CI_COMMIT_BRANCH}
      fi
    - ./semantic-release $SEMREL_OPTIONS
    - |
      NEW_SHA=$(git rev-parse HEAD)
      for i in {1..20}; do
        if git ls-remote https://github.com/$GITHUB_REPOSITORY | grep $NEW_SHA; then
          break
        fi
        sleep 5
      done
    - git push https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY :refs/tags/v$VERSION
    - ./semantic-release --provider github $SEMREL_OPTIONS
  needs:
    - go-test
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.release-dist:
  image: "goreleaser/goreleaser:v2.14.3"
  stage: release
  resource_group: release-dist # only run one releaser at a time for resource limits
  allow_failure: true # semantic release exits with code 1 if there are no changes
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --config $GORELEASER_CONFIG --clean
  needs:
    - go-test
  rules:
    - if: $CI_COMMIT_TAG

release-dist-gitlab:
  extends: .release-dist
  variables:
    GORELEASER_CONFIG: .goreleaser.gitlab.yaml

release-dist-github:
  extends: .release-dist
  variables:
    GORELEASER_CONFIG: .goreleaser.github.yaml

release-helm-ghcr:
  image: alpine/helm:3.17.3
  stage: release
  variables:
    GIT_DEPTH: 0
  script:
    - apk add --no-cache make
    - make sync-deployment-crds
    - echo "$GHCR_TOKEN" | helm registry login ghcr.io -u "$GHCR_USER" --password-stdin
    - helm package config/deployment/ --version ${CI_COMMIT_TAG#v} --app-version ${CI_COMMIT_TAG}
    - helm push chantico-*.tgz oci://ghcr.io/chantico-project/charts
  needs:
    - go-test
  rules:
    - if: $CI_COMMIT_TAG

# Copy Gitlab image to Github using https://github.com/containers/skopeo?tab=readme-ov-file#copying-images
release-chantico-ghcr:
  image: quay.io/skopeo/stable
  stage: release
  before_script:
    - skopeo login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - skopeo login -u "$GHCR_USER" -p "$GHCR_TOKEN" ghcr.io
  script:
    - skopeo copy
        docker://$CI_REGISTRY_IMAGE/chantico:${CI_COMMIT_TAG}
        docker://ghcr.io/chantico-project/images/chantico:${CI_COMMIT_TAG}
  needs:
    - build-chantico
    - go-test
  rules:
    - if: $CI_COMMIT_TAG
