persistentVolumeClaimName: chantico-snmp-prometheus-volume-claim
prometheusRetention: 5h
snmpExporterAddress: chantico-snmp:9116
imagePullSecretName: "" # Set if pulled from private registry, otherwise leave empty
controller:
  include: true
  image:
    repository: "ghcr.io/chantico-project/images/chantico"
    tag: "" # defaults to Chart.version
pvc:
  include: true
  storageClassName: "csi-rbd"
  storage: 3Gi
  accessModes:
    - ReadWriteOnce

