name: Release

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  # GoReleaser
  release:
    runs-on: ubuntu-latest
    continue-on-error: true
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7.2.1
        with:
          version: latest
          args: release --config .goreleaser.github.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Helm release
  helm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Helm
        uses: azure/setup-helm@v5

      - name: Package and push chart
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          VERSION=${GITHUB_REF#refs/tags/v}
          helm package config/deployment/ --version $VERSION --app-version v$VERSION
          helm push chantico-*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
